export const GUIDE_UI_TOKENS = Object.freeze({
  typography: {
    pageTitlePx: 30,
    sectionTitlePx: 22,
    cardTextPx: 18,
    bodyPx: 16,
    secondaryPx: 14,
  },
  spacing: {
    mobilePagePaddingPx: 16,
    mobilePagePaddingWidePx: 20,
    cardPaddingPx: 16,
    cardPaddingWidePx: 20,
    rowGapPx: 10,
    sectionGapPx: 20,
  },
  radius: {
    cardPx: 18,
    pillPx: 999,
  },
  touch: {
    minTargetPx: 44,
    bottomNavMinPx: 64,
    bottomNavMaxPx: 72,
  },
  color: {
    forest: '#173F35',
    forestStrong: '#103229',
    sage: '#8DAA9D',
    sageSoft: '#E8F0EC',
    warmWhite: '#FAF8F3',
    surface: '#FFFFFF',
    text: '#1D2A26',
    muted: '#63726C',
    attention: '#C46A2D',
    attentionSoft: '#FFF0E4',
    destructive: '#B42318',
    destructiveSoft: '#FEE4E2',
    positive: '#237A57',
    positiveSoft: '#E5F5ED',
    border: '#DCE5E0',
  },
} as const);

export const GUIDE_UI_CLASSES = Object.freeze({
  page: 'mx-auto min-w-0 w-full max-w-3xl px-4 pb-24 pt-5 sm:px-5',
  pageTitle: 'text-[30px] leading-tight font-bold tracking-tight text-[#173F35]',
  sectionTitle: 'text-[22px] leading-tight font-bold tracking-tight text-[#173F35]',
  cardText: 'text-[18px] leading-normal font-semibold text-[#1D2A26]',
  body: 'text-[16px] leading-normal text-[#1D2A26]',
  bodyMuted: 'text-[16px] leading-normal text-[#63726C]',
  secondary: 'text-[14px] leading-normal text-[#63726C]',
  card: 'min-w-0 rounded-[18px] border border-[#DCE5E0] bg-white shadow-sm',
  cardPadding: 'p-4 sm:p-5',
  metricCard: 'min-w-0 rounded-[18px] border border-[#DCE5E0] bg-[#FAF8F3] p-4',
  metricValue: 'mt-1 text-[28px] font-bold leading-none text-[#173F35] tabular-nums',
  insetSurface: 'rounded-[18px] bg-[#FAF8F3] p-4',
  interactiveCard:
    'rounded-[18px] border border-[#DCE5E0] bg-white p-4 text-left transition-[border-color,box-shadow,transform] duration-150 hover:border-[#8DAA9D] hover:shadow-sm active:translate-y-px disabled:cursor-not-allowed disabled:opacity-50 sm:p-5',
  quietSurface: 'rounded-[18px] border border-[#DCE5E0] bg-[#FAF8F3] p-4 sm:p-5',
  avatarSurface: 'bg-[#E8F0EC] text-[#173F35]',
  focusAttentionSurface: 'bg-[#FFF0E4] text-[#9B4F1F]',
  focusDangerSurface: 'bg-[#FEE4E2] text-[#B42318]',
  subtleSurface: 'bg-[#FAF8F3]',
  divider: 'divide-[#DCE5E0] border-[#DCE5E0]',
  settingsLink: 'text-[#1D2A26] transition-colors hover:bg-[#FAF8F3]',
  mutedIcon: 'text-[#63726C]',
  focusRing: 'outline-none focus-visible:ring-2 focus-visible:ring-[#173F35] focus-visible:ring-offset-2',
  detailFocusTarget: 'min-w-0 rounded-[18px] outline-none focus-visible:ring-2 focus-visible:ring-[#173F35] focus-visible:ring-offset-2',
  mobileScroll: 'min-w-0 max-w-full overflow-x-auto overscroll-x-contain',
  calendarGrid: 'grid min-w-0 grid-cols-7 gap-0',
  weekGrid: 'grid min-w-0 grid-cols-7 gap-0',
  weekdayLabel: 'min-w-0 whitespace-normal break-words text-[14px] font-semibold leading-tight',
  weekDate: 'min-w-0 whitespace-normal break-words text-[16px] font-bold leading-tight',
  weekCount: 'mt-1 min-w-0 whitespace-normal break-words text-center text-[14px] leading-tight',
  iconButton: 'inline-flex items-center justify-center rounded-xl text-[#63726C] hover:bg-[#FAF8F3]',
  primaryButton: 'inline-flex items-center gap-2 rounded-xl bg-[#173F35] px-4 text-[16px] font-semibold text-white',
  secondaryButton: 'inline-flex items-center gap-2 rounded-xl border border-[#DCE5E0] bg-white px-4 text-[16px] font-semibold text-[#173F35]',
  accentButton: 'inline-flex items-center rounded-xl bg-[#E8F0EC] px-4 text-[16px] font-semibold text-[#173F35]',
  searchInput: 'min-h-[48px] w-full rounded-xl pl-11 pr-11 text-[16px]',
  filterButton: 'inline-flex flex-1 items-center justify-center gap-1.5 rounded-full border px-3 text-[16px] font-semibold sm:flex-none',
  filterActive: 'border-[#173F35] bg-[#173F35] text-white',
  filterInactive: 'border-[#DCE5E0] bg-white text-[#1D2A26] hover:bg-[#FAF8F3]',
  filterCountActive: 'text-white/80',
  filterCountInactive: 'text-[#63726C]',
  listDivider: 'divide-[#DCE5E0]',
  travelerRow: 'flex min-h-[68px] w-full items-center rounded-xl text-left outline-none transition-colors hover:bg-[#FAF8F3] focus-visible:ring-2 focus-visible:ring-[#173F35] focus-visible:ring-offset-2',
  viewToggle: 'rounded-xl border px-3 text-[16px] font-semibold',
  viewToggleActive: 'border-[#173F35] bg-[#173F35] text-white',
  viewToggleInactive: 'border-[#DCE5E0] bg-white text-[#1D2A26]',
  outlinedIconButton: 'rounded-xl border border-[#DCE5E0] bg-white p-2 text-[#173F35]',
  filterPill: 'shrink-0 rounded-full border px-4 text-[16px] font-semibold',
  filterPillActive: 'border-[#8DAA9D] bg-[#E8F0EC] text-[#173F35]',
  filterPillInactive: 'border-[#DCE5E0] bg-white text-[#63726C]',
  calendarWeekday: 'py-1 text-center text-[14px] font-semibold text-[#63726C]',
  calendarCell: 'flex min-h-[60px] min-w-0 flex-col items-center justify-center rounded-xl border px-1 py-2 text-center whitespace-normal break-words',
  calendarSelected: 'border-[#173F35] bg-[#173F35] text-white',
  calendarInMonth: 'border-[#DCE5E0] bg-white text-[#1D2A26]',
  calendarOutside: 'border-transparent bg-[#FAF8F3] text-[#A2AEA8]',
  calendarDate: 'min-w-0 whitespace-normal break-words text-[16px] font-bold leading-tight',
  calendarCount: 'mt-1 min-w-0 whitespace-normal break-words text-center text-[14px] leading-tight',
  navShell: 'border-[#DCE5E0] bg-white/95',
  navActive: 'bg-[#E8F0EC] text-[#173F35]',
  navInactive: 'text-[#63726C]',
  calendarDayActive: 'bg-[#173F35] text-white',
  calendarDayIdle: 'bg-[#F3F6F4] text-[#1D2A26]',
  touchTarget: 'min-h-[44px] min-w-[44px]',
  sectionGap: 'space-y-5',
  rowGap: 'gap-2.5',
  messageOutgoing: 'bg-[#173F35] text-white',
  messageIncoming: 'bg-[#FAF8F3] text-[#1D2A26]',
  textInput: 'min-h-[48px] rounded-xl border border-[#DCE5E0] bg-white px-3 py-2 text-[16px] leading-normal',
  searchField: 'border border-[#DCE5E0] bg-white',
  dangerText: 'text-[#B42318]',
} as const);

export type GuideStatusTone = 'neutral' | 'positive' | 'attention' | 'danger' | 'info';

export const GUIDE_STATUS_CLASSES: Readonly<Record<GuideStatusTone, string>> = Object.freeze({
  neutral: 'border-[#DCE5E0] bg-[#F3F6F4] text-[#52615B]',
  positive: 'border-[#CDE8DA] bg-[#E5F5ED] text-[#237A57]',
  attention: 'border-[#F7D8BF] bg-[#FFF0E4] text-[#9B4F1F]',
  danger: 'border-[#F5C7C2] bg-[#FEE4E2] text-[#B42318]',
  info: 'border-[#CFE1D8] bg-[#E8F0EC] text-[#173F35]',
});
