-- #169 — restore the block-times page fields that Sol's earlier audit had
-- stripped from the frontend (title / weekly recurrence / full-day / auto)
-- instead of wiring them up. Owner-authorized, additive-only migration:
-- five new nullable-or-defaulted columns on the existing block_times table
-- (0004:115-124). Nothing existing is renamed, dropped, or narrowed, so
-- every already-migrated environment stays valid without a backfill step.
--
-- Schema drift note (Sol audit, 2026-09-04): both TEST (nmwhwngojosmagjuvxol)
-- and PRODUCTION (egehnijjpgijmccagxac) already carry these exact five
-- columns + both check constraints, applied outside the migration ledger by
-- an unknown prior process. This file's job on those two projects is to be a
-- true no-op that lets the repo's migration history match live schema — NOT
-- to change Production. Every statement below is written idempotent
-- (add column if not exists; constraints guarded by existence checks) so a
-- fresh database, TEST, and Production all converge on the identical result
-- whether or not the columns were already there. Constraint names below are
-- copied verbatim from what's live: block_times_recurrence_chk,
-- block_times_day_of_week_chk — do not rename them, or a freshly-built
-- database's schema stops matching TEST/Production's.
--
-- Semantics (see docs/integration/04-API-CONTRACTS.md and
-- src/app/api/block-times/route.ts for the read/write contract):
--   title        — display name, independent from `reason` (free text).
--   recurrence   — 'SINGLE' (the literal start_at/end_at interval) or
--                  'WEEKLY' (start_at/end_at give the *first* occurrence's
--                  date + time-of-day; day_of_week is authoritative for
--                  which weekday it repeats on). Expanded at query time by
--                  src/server/block-times.ts — no materialized future rows.
--   day_of_week  — 0 (Sunday) .. 6 (Saturday), same value domain as the
--                  original site's btDayOfWeek option value / JS getDay().
--                  Required for WEEKLY, null for SINGLE.
--   full_day     — the row's original "整天封鎖" checkbox intent. start_at/
--                  end_at still carry the real interval (kept queryable);
--                  this flag is what the edit form uses to re-check the box.
--   auto         — true for rows generated by "每天不同營業時間" (business
--                  hours automation, not part of this slice). Rows with
--                  auto = true are read-only: PUT/DELETE on them must be
--                  rejected by the API layer (409), enforced in app code
--                  since Postgres RLS here is tenant-scoped, not row-flag-scoped.

alter table block_times add column if not exists title text not null default '';
alter table block_times add column if not exists recurrence text not null default 'SINGLE';
alter table block_times add column if not exists day_of_week smallint;
alter table block_times add column if not exists full_day boolean not null default false;
alter table block_times add column if not exists auto boolean not null default false;

do $$
begin
  alter table block_times add constraint block_times_recurrence_chk
    check (recurrence = any (array['SINGLE'::text, 'WEEKLY'::text]));
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table block_times add constraint block_times_day_of_week_chk
    check (day_of_week is null or (day_of_week >= 0 and day_of_week <= 6));
exception when duplicate_object then null;
end $$;
