import { describe, expect, it } from 'vitest';
import { TEST_PARENT_PROJECT_REF, classifyRemoteBranchRequirement, cleanupDecision, determineFullTerraCapacity, estimateBranchCost, expectedBranchName, validateBranchLease, validateLeaseSet } from '../../scripts/ci/supabase-branch-lease-policy.mjs';
const HEAD='a'.repeat(40);
function planned(overrides:Record<string,unknown>={}){return {schemaVersion:1,mode:'SUPABASE_PREVIEW_BRANCH_LEASE',leaseId:'pr-120-slot-1',status:'PLANNED',parentProjectRef:TEST_PARENT_PROJECT_REF,pullRequest:120,exactHead:HEAD,branchName:'pr-120-aaaaaaaa',testProfile:'REMOTE_BRANCH_REQUIRED',slot:1,branchId:null,projectRef:null,createdAt:null,expiresAt:null,hourlyCostUsd:null,estimatedCostUsd:null,costConfirmedAt:null,costConfirmationEvidence:null,cleanupOwner:'bplus-loop',cleanupStatus:'NOT_CREATED',destroyedAt:null,migrationBaseline:null,notes:[],...overrides};}
function active(overrides:Record<string,unknown>={}){return planned({status:'ACTIVE',branchId:'branch-1',projectRef:'preview-project-1',createdAt:'2026-09-01T10:00:00Z',expiresAt:'2026-09-01T11:30:00Z',hourlyCostUsd:0.01344,estimatedCostUsd:0.02016,costConfirmedAt:'2026-09-01T09:59:00Z',costConfirmationEvidence:'Owner confirmed live hourly cost and max two branches',cleanupStatus:'PENDING',migrationBaseline:'main@abc + migrations through 0062',...overrides});}
describe('Supabase Preview Branch lease policy',()=>{
it('classifies DB, Auth and Storage paths',()=>expect(classifyRemoteBranchRequirement(['supabase/migrations/0063_x.sql','src/app/api/auth/callback/route.ts','src/app/api/upload/route.ts'])).toEqual({required:true,reasons:['DATABASE_MIGRATION','AUTH','STORAGE']}));
it('uses deterministic branch names',()=>expect(expectedBranchName(120,HEAD)).toBe('pr-120-aaaaaaaa'));
it('accepts a planned lease',()=>expect(validateBranchLease(planned())).toMatchObject({valid:true,errors:[]}));
it('requires cost, baseline and cleanup ownership',()=>{const r=validateBranchLease(active({costConfirmedAt:null,costConfirmationEvidence:null,migrationBaseline:null,cleanupOwner:null}),{now:new Date('2026-09-01T10:10:00Z')});expect(r.errors).toEqual(expect.arrayContaining(['active lease requires costConfirmedAt','active lease requires costConfirmationEvidence','active lease requires cleanupOwner','active lease requires migrationBaseline']));});
it('rejects long or expired leases',()=>{expect(validateBranchLease(active({expiresAt:'2026-09-01T12:30:00Z'}),{now:new Date('2026-09-01T10:10:00Z')}).errors).toContain('lease duration exceeds 120 minutes');expect(validateBranchLease(active(),{now:new Date('2026-09-01T12:00:00Z')}).errors).toContain('active lease is expired and must enter cleanup');});
it('rejects committed secrets',()=>expect(validateBranchLease(active({accessToken:'forbidden'}),{now:new Date('2026-09-01T10:10:00Z')}).errors.some((e:string)=>e.includes('must not store secrets'))).toBe(true));
it('enforces max two and unique slots',()=>{const a=active();const b=active({leaseId:'b',pullRequest:121,exactHead:'b'.repeat(40),branchName:'pr-121-bbbbbbbb',slot:2,branchId:'branch-2',projectRef:'preview-2'});expect(validateLeaseSet([a,b],{now:new Date('2026-09-01T10:10:00Z')}).valid).toBe(true);const c=active({leaseId:'c',pullRequest:122,exactHead:'c'.repeat(40),branchName:'pr-122-cccccccc',slot:2,branchId:'branch-3',projectRef:'preview-3'});expect(validateLeaseSet([a,b,c],{now:new Date('2026-09-01T10:10:00Z')}).errors).toEqual(expect.arrayContaining(['duplicate active slot: 2','active Supabase Preview Branch leases 3; maximum is 2']));});
it('separates delete request from destruction proof',()=>{expect(cleanupDecision({lease:active({status:'CLEANUP_PENDING',cleanupStatus:'REQUESTED_UNVERIFIED'}),liveBranchIds:['branch-1'],now:new Date('2026-09-01T10:10:00Z')})).toMatchObject({action:'DELETE_REQUIRED'});expect(cleanupDecision({lease:active({status:'CLEANUP_PENDING',cleanupStatus:'REQUESTED_UNVERIFIED'}),liveBranchIds:[],now:new Date('2026-09-01T10:10:00Z')})).toMatchObject({action:'VERIFY_DESTROYED'});});
it('calculates cost',()=>expect(estimateBranchCost(active())).toBe(0.02016));
it('keeps Phase 3 closed until every gate passes',()=>{expect(determineFullTerraCapacity({phase1bVerified:true,remoteBranchLifecycleVerified:false,healthyIsolatedSlots:2})).toMatchObject({maxFullTerra:1,mode:'SINGLE'});expect(determineFullTerraCapacity({phase1bVerified:true,remoteBranchLifecycleVerified:true,healthyIsolatedSlots:2,completedObservationRuns:0})).toMatchObject({maxFullTerra:2,mode:'DUAL_PILOT',defaultGate:false});expect(determineFullTerraCapacity({phase1bVerified:true,remoteBranchLifecycleVerified:true,healthyIsolatedSlots:2,completedObservationRuns:3})).toMatchObject({maxFullTerra:2,mode:'DUAL_DEFAULT',defaultGate:true});});
});
